---
title: "Tabela 3: Domicílios com saneamento inadequado e classe populacional, agregado por Mesorregião"
format: pdf
editor: visual
---

```{r,echo=FALSE}
library(knitr)

niveis<- c('Baixadas', 'Centro', 'Metropolitana', 'Noroeste', 'Norte', 'Sul')
nomes<- c("Município","Saneamento Inadequado(%)","Classe Populacional")
tabela <- read.csv2("D:/Documentos (D)/UFJF/6-PERIODO/TCCI/DADOS IBGE/ProjIBGE/dados/RJ/TabRJ.csv")
tabela$Classe <- as.factor(tabela$Classe)
tabela$Microrregiao <-as.factor(tabela$Microrregiao)
tabela$Mesorregiao <-as.factor(tabela$Mesorregiao)
levels(tabela$Mesorregiao) <- niveis
levels(tabela$Classe) <- c(">500 mil","[10 mil, 20 mil)",
        "[100 mil, 500 mil)", "[20 mil, 50 mil)","[5 mil, 10 mil)",
        "[50 mil, 100 mil)")
#tab <- subset(tabela, subset=Mesorregiao=="Baixadas", select= c("Municipio","ValMedio","Q2","Mediana","Q3"))
tabs <- list()
for(reg in niveis){
  tabs[[paste0("tab",reg)]] <- subset(tabela,
              subset=Mesorregiao==reg,
              select= c("Municipio","Inadequado","Classe"))
  rownames(tabs[[paste0("tab",reg)]]) <- NULL
}
```

# Baixadas Litorâneas

```{r,echo=FALSE}

kable(tabs$tabBaixadas,row.names=NA,
      col.names=nomes)
```

# Centro

```{r,echo=FALSE}
kable(tabs$tabCentro,row.names=NA,
      col.names=nomes)
```

# Região Metropolitana

```{r,echo=FALSE}
kable(tabs$tabMetropolitana,row.names=NA,
      col.names=nomes)
```

# Noroeste Fluminense

```{r,echo=FALSE}
kable(tabs$tabNoroeste,row.names=NA,
      col.names=nomes)
```

\vspace{1in}

# Norte Fluminse

```{r,echo=FALSE}
kable(tabs$tabNorte,row.names=NA,
      col.names=nomes)
```

# Sul Fluminense

```{r,echo=FALSE}
kable(tabs$tabSul,row.names=NA,
      col.names=nomes)
```
