---
title: "Tabela 2: Rendimento em reais médio e mediano por sexo nos municípios do estado do Rio de Janeiro"
format: pdf
editor: visual
---

```{r,echo=FALSE}
suppressMessages({
  library(dplyr,quietly = T)
  library(kableExtra)}
)
cor <- "#E3E3E3"
niveis<- c('Baixadas', 'Centro', 'Metropolitana', 'Noroeste', 'Norte', 'Sul')
nomes<- c("Município","Média\nMasculina","Média\nFeminina", "Mediana\nMasculina",
                  "Mediana\nFeminina")
tabela <- read.csv2("D:/Documentos (D)/UFJF/6-PERIODO/TCCI/DADOS IBGE/ProjIBGE/dados/RJ/TabRJ.csv")
tabela$Classe <- as.factor(tabela$Classe)
tabela$Microrregiao <-as.factor(tabela$Microrregiao)
tabela$Mesorregiao <-as.factor(tabela$Mesorregiao)
levels(tabela$Mesorregiao) <- niveis

#tab <- subset(tabela, subset=Mesorregiao=="Baixadas", select= c("Municipio","ValMedio","Q2","Mediana","Q3"))
tabs <- list()
for(reg in niveis){
  tabs[[paste0("tab",reg)]] <- subset(tabela,
              subset=Mesorregiao==reg,
              select= c("Municipio","MediaHomens","MediaMulheres","MedianaHomens","MedianaMulheres"))
  rownames(tabs[[paste0("tab",reg)]]) <- NULL
}
```

# Baixadas Litorâneas

```{r,echo=FALSE}
kbl(tabs$tabBaixadas,format="latex",escape=F,longtable=T,row.names=NA,
      col.names=linebreak(nomes),booktabs=T) %>% 
  kable_styling(full_width = F,                                         latex_options=c("hold_position","striped","repeat_header"),
                stripe_color=cor,
                repeat_header_text = "\\textit{(continuada)}")
```

# Centro Fluminense

```{r,echo=FALSE}
kbl(tabs$tabCentro,format="latex",escape=F,longtable=T,row.names=NA,
      col.names=linebreak(nomes),booktabs=T) %>% 
  kable_styling(full_width = F,                                         latex_options=c("hold_position","striped","repeat_header"),
                stripe_color=cor,
                repeat_header_text = "\\textit{(continuada)}")
```

# Metropolitana do Rio de Janeiro

```{r,echo=FALSE}
kbl(tabs$tabMetropolitana,format="latex",escape=F,longtable=T,row.names=NA,
      col.names=linebreak(nomes),booktabs=T) %>% 
  kable_styling(full_width = F,                                         latex_options=c("hold_position","striped","repeat_header"),
                stripe_color=cor,
                repeat_header_text = "\\textit{(continuada)}")
```

# Noroeste Fluminense

```{r,echo=FALSE}
kbl(tabs$tabNoroeste,format="latex",escape=F,longtable=T,row.names=NA,
      col.names=linebreak(nomes),booktabs=T) %>% 
  kable_styling(full_width = F,                                         latex_options=c("hold_position","striped","repeat_header"),
                stripe_color=cor,
                repeat_header_text = "\\textit{(continuada)}")
```

\vspace{0.5in}

# Norte Fluminse

```{r,echo=FALSE}
kbl(tabs$tabNorte,format="latex",escape=F,longtable=T,row.names=NA,
      col.names=linebreak(nomes),booktabs=T) %>% 
  kable_styling(full_width = F,                                         latex_options=c("hold_position","striped","repeat_header"),
                stripe_color=cor,
                repeat_header_text = "\\textit{(continuada)}")
```

# Sul Fluminense

```{r,echo=FALSE}
kbl(tabs$tabSul,format="latex",escape=F,longtable=T,row.names=NA,
      col.names=linebreak(nomes),booktabs=T) %>% 
  kable_styling(full_width = F,                                         latex_options=c("hold_position","striped","repeat_header"),
                stripe_color=cor,
                repeat_header_text = "\\textit{(continuada)}")
```
